export const Users = [
    {
      id:1,
      profilePicture: "ashfan.jpg",
      username: "Aryan Mahajan",
    },
    {
      id:2,
      profilePicture: "arole.jpg",
      username: "Ashfan Khan",
    },
    {
      id:3,
      profilePicture: "arole.jpg",
      username: "Rohit Arole",
    },
    {
      id:4,
      profilePicture: "ashfan.jpg",
      username: "Chinmayee Awale",
    },
    {
      id:5,
      profilePicture: "mahajan.jpg",
      username: "Atharva Mugalikar",
    },
    {
      id:6,
      profilePicture: "koshatwar.jpg",
      username: "Aryan Koshatwar",
    },
    {
      id:7,
      profilePicture: "ashfan.jpg",
      username: "Ayushi Khare",
    },
    {
      id:8,
      profilePicture: "Anish.jpg",
      username: "Arunav Chandra",
    },
    {
      id:9,
      profilePicture: "ashfan.jpg",
      username: "Rohit Sharma",
    },
    {
      id:10,
      profilePicture: "ashfan.jpg",
      username: "Virat Kohli",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885__480.jpg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885__480.jpg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "https://images.unsplash.com/photo-1541963463532-d68292c34b19?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "ashfan.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "https://www.nature.com/immersive/d41586-021-00095-y/3TP4N718ac/2021-01-xx_jan-iom_tree-of-life_sh-1080x1440.jpeg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "https://image.shutterstock.com/image-photo/my-heart-bubbles-sky-sunsetlove-260nw-221010295.jpg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "https://static.toiimg.com/thumb/msid-31346158,width-748,height-499,resizemode=4,imgsize-114461/.jpg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "https://st.depositphotos.com/1428083/2946/i/600/depositphotos_29460297-stock-photo-bird-cage.jpg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOd256TcC6vcaQ99TYzoP0pBbch9_Q-bbrmw&usqp=CAU",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "https://helpx.adobe.com/content/dam/help/en/photoshop/using/convert-color-image-black-white/jcr_content/main-pars/before_and_after/image-before/Landscape-Color.jpg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];